version: "3.8"
services:
  Pgdb:
    image: postgres
    restart: always
    container_name: peabuxPgDb
    ports:
      - 5432:5432
    networks:
      - peabux_appnetwork
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AwesomePass_1234
      - POSTGRES_DB=PeabuxPg
    volumes:
      - pgdb-data:/var/lib/postgresql/data/
  pgadmin:
    depends_on:
      - Pgdb
    container_name: pgadmin4_ui
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: AwesomePass_1234
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8009:80"
    networks:
      - peabux_appnetwork
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  backend:
    depends_on:
      - Pgdb
    image: ${DOCKER_REGISTRY-}peabuxapipg
    container_name: peabux-APIpg
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=host=Pgdb;Port=5432;Database=PeabuxPg;User Id=postgres;Password=AwesomePass_1234;"
    ports:
      - 8086:6003
    networks:
      - peabux_appnetwork
volumes:
  pgdb-data:
    driver: local
  pgadmin-data:
    driver: local
networks:
  peabux_appnetwork:
    driver: bridge
